/* Copyright 2000, 2013 Neil Edelman, distributed under the terms of the
 GNU General Public License, see copying.txt */

#include <stdlib.h> /* exit */
#include <stdio.h>  /* fprintf */
#include <time.h>   /* srand(clock()) */
#include <string.h> /* strcmp */
#include "general/Map.h"
#include "EntryPosix.h"
#include "system/Window.h"
#include "system/Draw.h"
#include "system/Timer.h"
#include "system/Key.h"
#include "general/Bitmap.h"
#include "game/Game.h"

/* include hard-coded resources generated by tools/, see Makefile; this
 accounts for 99% of the compilation time */
#include "../bin/Ngc4038_4039_bmp.h"
#include "../bin/Asteroid_bmp.h"
#include "../bin/Nautilus_bmp.h"
#include "../bin/Scorpion_bmp.h"

/** Entry point for command-line, unix-like operating systems (ie, all of them.)
 <p>
 Fixme: have separate entry points for MacOS and Windows that are user friendly.
 @author	Neil
 @version	3.2, 2015-05
 @since		3.2, 2015-05 */

/* constants */
static const char *programme   = "Void";
static const char *year        = "2015";
static const int versionMajor  = 3;
static const int versionMinor  = 2;

static const int framelenght_ms = 20; /* 50 fps -- fixme: variable */

struct Entry {
	struct Map *bmps;
} entry;

static void main_(void);
static void usage(void);
static void delete_bitmap(char *key, struct Bitmap *bmp);

/** entry point
 @param argc the number of arguments starting with the programme name
 @param argv the arguments
 @return     either EXIT_SUCCESS or EXIT_FAILURE */
int main(int argc, char **argv) {
	struct Bitmap *bmp;

	/* fixme: more options! (ie, load game, etc) */
	if(argc > 1) {
		usage();
		return EXIT_SUCCESS;
	}

	/* we generally don't have return because glutMainLoop() never does */
	if(atexit(&main_)) perror("atexit");

	/* load in all bitmaps to a Map; fixme: compress! */
	if(!(entry.bmps = Map("bmp", (int (*)(const void *, const void *))strcmp))) return EXIT_FAILURE;
	MapSetDestructor(entry.bmps, (void (*)(void *, void *))delete_bitmap);
	if(!(bmp = Bitmap(Ngc4038_4039_bmp_width, Ngc4038_4039_bmp_height, Ngc4038_4039_bmp_depth, Ngc4038_4039_bmp_bmp, B_BACKGROUND))
	   || !MapPut(entry.bmps, Ngc4038_4039_bmp_name, bmp)) {
		Bitmap_(&bmp);
		return EXIT_FAILURE;
	}
	if(!(bmp = Bitmap(Asteroid_bmp_width, Asteroid_bmp_height, Asteroid_bmp_depth, Asteroid_bmp_bmp, B_SPRITE))
	   || !MapPut(entry.bmps, Asteroid_bmp_name, bmp)) {
		Bitmap_(&bmp);
		return EXIT_FAILURE;
	}
	if(!(bmp = Bitmap(Nautilus_bmp_width, Nautilus_bmp_height, Nautilus_bmp_depth, Nautilus_bmp_bmp, B_SPRITE))
	   || !MapPut(entry.bmps, Nautilus_bmp_name, bmp)) {
		Bitmap_(&bmp);
		return EXIT_FAILURE;
	}
	if(!(bmp = Bitmap(Scorpion_bmp_width, Scorpion_bmp_height, Scorpion_bmp_depth, Scorpion_bmp_bmp, B_SPRITE))
	   || !MapPut(entry.bmps, Scorpion_bmp_name, bmp)) {
		Bitmap_(&bmp);
		return EXIT_FAILURE;
	}

	/* start up subsystems; window has to be first; timer ms */
	if(!Window(programme, argc, argv)
		|| !Key()
		|| !Draw(entry.bmps) /* fixme: don't need the arg */
	    || !Game()
		|| !Timer(framelenght_ms)) return EXIT_FAILURE;
	/* entropy increase */
	srand((unsigned)clock());

	/* hand over control to the grahics library */
	WindowGo();

	/* never get here */
	return EXIT_FAILURE;
}

/** Destructor (called with atexit().) */
static void main_(void) {
	Timer_();
	Game_();
	Draw_(entry.bmps);
	if(entry.bmps) Map_(&entry.bmps);
}

struct Map *EntryGetBitmaps(void) {
	return entry.bmps;
}

/** Help screen. */
static void usage(void) {
	fprintf(stderr, "Usage: %s\n", programme);
	fprintf(stderr, "To win, blow up everything that's not you.\n");
	fprintf(stderr, "Player one controls: left, right, up, down, space\n");
	/* fprintf(stderr, "Player two controls: a, d, w, s, space.\n"); */
	fprintf(stderr, "Fullscreen: F1.\n");
	fprintf(stderr, "Exit: Escape.\n\n");
	fprintf(stderr, "Version %d.%d.\n\n", versionMajor, versionMinor);
	fprintf(stderr, "%s Copyright %s Neil Edelman\n", programme, year);
	fprintf(stderr, "This program comes with ABSOLUTELY NO WARRANTY.\n");
	fprintf(stderr, "This is free software, and you are welcome to redistribute it\n");
	fprintf(stderr, "under certain conditions; see copying.txt.\n\n");
}

/** callback for deleting bitmaps from the map */
static void delete_bitmap(char *key, struct Bitmap *bmp) {
	if(!bmp) {
		fprintf(stderr, "Warning: bitmap data null for key \"%s.\"\n", key);
		return;
	}
	Bitmap_(&bmp);
}
